import type { Profile } from "../args";

export interface VmScriptOptions {
  expoToken: string;
  profile: Profile;
  platform: "android" | "ios";
  submit: boolean;
  optimize: boolean;
  cacheEnabled: boolean;
  /** Tart --dir mount name for the synced source. */
  mountName: string;
  /** Mobile dir relative to the sync root; "" when they are the same. */
  mobileRelPath: string;
  javaVersion: string;
}

export const CACHE_MOUNT_NAME = "expo-builder-cache";

/** Where Tart exposes --dir mounts inside the guest. */
function mountPath(name: string): string {
  return `/Volumes/My Shared Files/${name}`;
}

export function generateVmScript(opts: VmScriptOptions): string {
  const {
    expoToken, profile, platform, submit, optimize, cacheEnabled,
    mountName, mobileRelPath, javaVersion,
  } = opts;

  const ext = platform === "ios" ? "ipa" : "aab";
  const artifact = `$HOME/out/app.${ext}`;
  const versionField = platform === "ios" ? "buildNumber" : "versionCode";
  const workDir = mobileRelPath ? `$HOME/work/${mobileRelPath}` : "$HOME/work";

  const lines: string[] = [
    "set -euo pipefail",
    `export PATH="$HOME/.bun/bin:/opt/homebrew/opt/openjdk@${javaVersion}/bin:/opt/homebrew/bin:/usr/local/bin:$PATH"`,
    `export JAVA_HOME="/opt/homebrew/opt/openjdk@${javaVersion}"`,
    'export ANDROID_HOME="$HOME/Library/Android/sdk"',
    `export EXPO_TOKEN="${expoToken}"`,
    "",
    "# EAS packages the project itself and honours .gitignore/.easignore,",
    "# so no git repository is needed on the builder.",
    "export EAS_NO_VCS=1",
    "",
  ];

  if (cacheEnabled) {
    const cache = mountPath(CACHE_MOUNT_NAME);
    lines.push(
      "# Shared, budget-bounded caches mounted from the Mac host",
      `export BUN_INSTALL_CACHE_DIR="${cache}/bun"`,
      `export CP_HOME_DIR="${cache}/cocoapods"`,
      `export GRADLE_USER_HOME="${cache}/gradle"`,
      'mkdir -p "$BUN_INSTALL_CACHE_DIR" "$CP_HOME_DIR" "$GRADLE_USER_HOME"',
      "",
    );
  } else {
    lines.push('export GRADLE_USER_HOME="$HOME/.gradle"', "");
  }

  // Stage source onto the VM's own disk. The mount is read-only and slow;
  // building in place would also leave node_modules and artifacts on the Mac.
  lines.push(
    'echo "::phase::stage"',
    'mkdir -p "$HOME/work" "$HOME/out"',
    `rsync -a --delete "${mountPath(mountName)}/" "$HOME/work/"`,
    `cd "${workDir}"`,
    "",
  );

  if (optimize) {
    lines.push(
      "# Inject the iOS build optimization plugin via an app.config wrapper",
      "if [ -f app.config.ts ]; then",
      "  mv app.config.ts _app.config.original.ts",
      "  cat > app.config.ts << 'PLUGINEOF'",
      "// @ts-nocheck — build-time wrapper, auto-generated by expo-builder",
      'import original from "./_app.config.original";',
      'const plug = "./plugins/withBuildOptimizations";',
      "const inject = (c: any) => ({ ...c, plugins: [...(c.plugins || []), plug] });",
      "export default typeof original === 'function' ? (...a: any[]) => inject((original as any)(...a)) : inject(original);",
      "PLUGINEOF",
      "fi",
      "",
    );

    if (platform === "android") {
      lines.push(
        "# Gradle tuning: dynamic heap, no lint, limited workers",
        'mkdir -p "$GRADLE_USER_HOME"',
        "TOTAL_MEM_GB=$(( $(sysctl -n hw.memsize) / 1024 / 1024 / 1024 ))",
        "JVM_MAX_GB=$(( TOTAL_MEM_GB > 4 ? TOTAL_MEM_GB - 2 : 2 ))",
        'cat > "$GRADLE_USER_HOME"/gradle.properties << GEOF',
        "org.gradle.caching=true",
        "org.gradle.workers.max=2",
        "reactNativeArchitectures=arm64-v8a",
        "org.gradle.jvmargs=-Xmx${JVM_MAX_GB}g -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError",
        "GEOF",
        `cat > "$GRADLE_USER_HOME"/init.gradle << 'GEOF'`,
        "allprojects {",
        "    afterEvaluate {",
        "        tasks.matching { it.name.contains('lintVital') }.configureEach {",
        "            enabled = false",
        "        }",
        "    }",
        "}",
        "GEOF",
        "",
      );
    }
  }

  lines.push(
    'echo "::phase::env-pull"',
    `eas env:pull --environment ${profile} --non-interactive`,
    "",
    'echo "::phase::install"',
    "bun install --frozen-lockfile",
    "",
    'echo "::phase::build"',
    "[ ! -f .env.local ] && touch .env.local",
    `dotenv -e .env.local -- eas build --local --platform ${platform} --profile ${profile} --output ${artifact} --non-interactive 2>&1`,
    "",
    'echo "::phase::version"',
    `VERSION_JSON=$(eas build:version:get -p ${platform} --profile ${profile} --json --non-interactive 2>/dev/null || echo '{}')`,
    `CUR=$(echo "$VERSION_JSON" | bun -e "const d=JSON.parse(await Bun.stdin.text()); process.stdout.write(String(d.${versionField}??0))")`,
    "NEXT=$((CUR + 1))",
    'echo "::version::$CUR → $NEXT"',
    `echo "$NEXT" | eas build:version:set -p ${platform} --profile ${profile} || echo "::error::Version increment failed"`,
  );

  if (submit) {
    lines.push(
      "",
      'echo "::phase::submit"',
      `eas submit --platform ${platform} --profile ${profile} --path ${artifact} --non-interactive`,
    );
  }

  return lines.join("\n");
}
